### ISSUE TITLE
bad endpoint for rack info

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#162]
see https://rollbar.com/joyent_buildops/conch/items/86/ and https://rollbar.com/joyent_buildops/conch/items/87. An endpoint is being hit that was removed in #796.

**Comment by karenetheridge** [comment]
This can be seen in the "Browse" menu by clicking on a rack name.

Also reported back in #118.

**Comment by dustinryerson** [comment]
All workspace API endpoints have been removed in the UI.
