### ISSUE TITLE
after creating a user, stuck in infinite spinner

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#171]
This is at https://conch.joyent.us/#/admin/users. No screenshot because it contains sensitive information.  After clicking "create user" in the large green bar, the spinner icon comes up and never returns.

**Comment by karenetheridge** [comment]
This occurred again today while attempting to create a user while away from my regular workstation.

**Comment by karenetheridge** [comment]
I could not add an existing user to a workspace either -- same infinite spinner on submisison.

**Comment by dustinryerson** [comment]
Resolved in [v3.0.13](https://github.com/joyent/conch-ui/releases/tag/v3.0.13).
