### ISSUE TITLE
need for GET /validation endpoint?

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#174]
A while ago you asked me to include deactivated validations in `GET /validation`. It would appear you're using this endpoint to populate the validations pane when showing information for a particular device.  What information do you need from that endpoint that isn't already in `GET /device/:id/validation_state`? The intent is that everything you need is in the latter endpoint. We should fix this.

**Comment by dustinryerson** [comment]
`GET /validation` endpoints have been removed, so this is no longer needed.
