### ISSUE TITLE
rack assignment modal "save" button doesn't trigger anything

### ISSUE THREAD

**Issue by perigrin** [joyent/conch-ui#181]
When trying to edit a rack assignment, clicking on the Save button at the bottom of the modal doesn't appear to do anything. I get the following in the console:

```
ReferenceError: "regeneratorRuntime is not defined"
    saveModifiedAssignments EditLayoutModal.vue:362
    click EditLayoutModal.vue:385
    VueJS 3
        Wt
        o
        _wrapper
vue.esm.js:1897
    VueJS 6
```

**Comment by dustinryerson** [comment]
Resolved in [v3.0.13](https://github.com/joyent/conch-ui/releases/tag/v3.0.13).
