### ISSUE TITLE
after editing user, modal never finishes.

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#209]
After clicking 'edit user', and then clicking through the edit workspaces pane, the POST request submits to the API, and a http 200 is returned, but the spinner never ends.

[screenshot](https://www.dropbox.com/s/z0fnvarsn882hwp/Screenshot%202020-04-16%2017.22.37.png?dl=0)

(this is on production)

**Comment by dustinryerson** [comment]
The workspace parts of the Edit User flow have been removed, but the overall UX of editing a user needs improvement. I've opened a new ticket for it here: https://github.com/joyent/conch-ui/issues/209

**Comment by karenetheridge** [comment]
#209 is *this* ticket.

**Comment by dustinryerson** [comment]
Correct ticket: https://github.com/joyent/conch-ui/issues/283
