### ISSUE TITLE
"Builds" link does not work for non-systemadmins

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#235]
Clicking on "Builds" in the left sidebar as an unprivileged user results in an infinite spinner for many of the build cells (every build that the user doesn't have the ability to view). Information is bleeding over from previous logins where a different user could see more builds, and the UI is attempting to populate data for all those builds as well, rather than just the builds returned from `GET /build` (which is restricted to those the user has permissions for).

**Comment by karenetheridge** [comment]
Similarly, clicking "Profile" also hangs -- in the console I see submitted to the API: `GET .../user/undefined/token` and `GET .../user/<wrong userid>`, both of which return 403.

**Comment by karenetheridge** [comment]
After logging out and logging in again, now "Profile" shows user data for the wrong user instead of just hanging.

**Comment by karenetheridge** [comment]
This is still occurring today.

**Comment by dustinryerson** [comment]
This is fixed in production.
