### ISSUE TITLE
errors when trying to change own user's username

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#242]
after editing the user name and clicking submit, an error occurs. see screenshot:

https://www.dropbox.com/s/ithudu11mgbc1sl/Screen%20Shot%202020-08-27%20at%2011.46.01%20AM.png?dl=0

![Screen Shot 2020-08-27 at 11 46 01 AM](https://user-images.githubusercontent.com/303051/91484030-6c9c3300-e85d-11ea-88be-16afdeb3874d.png)

**Comment by karenetheridge** [comment]
this issue seems to still exist.

**Comment by dustinryerson** [comment]
I've verified that this has been fixed on production. Please feel free to reopen if I've missed something.
