### ISSUE TITLE
adding links: errors are not cleared after a subsequent successful entry

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#245]
When adding a link, and the link is in the wrong format, an error is displayed. Then, after successfully adding a link, the previous error is not cleared.

Also, GET /device/:id is called twice after the link is POSTed.

![Screen Shot 2020-08-28 at 3 04 32 PM](https://user-images.githubusercontent.com/303051/91618719-fd4b3f80-e93f-11ea-82b2-a4357470f6af.png)

**Comment by karenetheridge** [comment]
this issue seems to still exist.

**Comment by dustinryerson** [comment]
Just tested this on edge and it's working now. I added a poorly formatted link, clicked the Add Link button and got the error message. I then entered a properly formatted link, clicked the Add Link button and the link was added and the error message was removed.

**Comment by dustinryerson** [comment]
I've verified that this has been fixed on production. Please feel free to reopen if I've missed something.
