### ISSUE TITLE
validation results not displaying

### ISSUE THREAD

**Issue by perigrin** [joyent/conch-ui#246]
If you open any device and look at the "validations' tab, the list is empty.

I discovered this when I was checking the device I managed to get reporting from production:

https://edge.conch.joyent.us/#/devices/d6877d79-4375-4861-a032-03cb2b14a670

But when I checked other devices I saw the same behavior:

https://edge.conch.joyent.us/#/devices/b2661366-2c5f-41f6-9e35-362b104460ef

**Comment by dustinryerson** [comment]
I've verified that this has been fixed on production. Please feel free to reopen if I've missed something.
