### ISSUE TITLE
Show in Rack from Device Panel

### ISSUE THREAD

**Issue by perigrin** [joyent/conch-ui#254]
When you're loaded to a single device (e.g. https://edge.conch.joyent.us/#/devices/c3f0cf4f-1818-456d-914a-7ee5df2a8e18 ) there is (sometimes?) no link back to the rack / datacenter view for the device. There is in fact, as far as I can tell,  no rack or location information to even *find* the rack that a given device is in

This is an important navigation to understand the device in the larger context.

We need to ensure that the "show device in rack" button is always present and functional in the device page so we can navigate up to a higher context.

**Comment by dustinryerson** [comment]
After discussing this with Chris, it's apparent that some devices in Conch don't have a location reference. Currently, if a device doesn't have a location reference, the "Show Device in Rack" button is hidden. Based on our discussion, I'll change the behavior of the button. If a device does not have a location reference, I'll keep the button on the overview tab of the device inspector and disable it with a popover stating that the device does not have a known location.

**Comment by dustinryerson** [comment]
I've verified that this is fixed in production. Please feel free to reopen if I've missed something.
