### ISSUE TITLE
Add Rack Unit to device list

### ISSUE THREAD

**Issue by perigrin** [joyent/conch-ui#258]
The Device List panel doesn't include the Rack Unit, even when navigating to the list from by clicking on a rack in the Rack List. Knowing which RU the device is in is kinda vital information when communicating with DCOps or anyone about which devices in the rack. 

Can we get the rack unit put into the first column of the device rack view and  sort by the rack order (rack units start at 0 on the floor so a descending numerical sort will work)? 

If we're showing multiple racks at a time sorting by Rack Number + Rack Unit would be nice as a default.

**Comment by dustinryerson** [comment]
I've verified that this has been deployed to production. Please feel free to reopen if I've missed something.
