### ISSUE TITLE
invalid email address during login does not show error for user

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#261]
If the user doesn't enter a valid email address at the login page, it appears as if the form submission didn't work. In fact, the API returned a 400 error that is not being handled properly.

![Screen Shot 2020-09-24 at 2 33 32 PM](https://user-images.githubusercontent.com/303051/94202805-35786c00-fe73-11ea-9498-7dccb2004809.png)

**Comment by karenetheridge** [comment]
related: #196

**Comment by dustinryerson** [comment]
I've verified that this has been fixed on production. Please feel free to reopen if I've missed something.

<img width="800" alt="Screen Shot 2020-12-22 at 2 24 40 PM" src="https://user-images.githubusercontent.com/2080476/102938650-91966080-4461-11eb-9a8b-ad4146bfabf7.png">
