### ISSUE TITLE
Add a "Last Reported" column on the device list panel

### ISSUE THREAD

**Issue by perigrin** [joyent/conch-ui#263]
When looking at the device list it would be incredibly useful to know when the last report was sent for a given device. Adding a column after "hardware product" of "last reported" that mirrored the same field inside the device info panel would be perfect. 

This let's me know at a glance how many devices are reporting in a given rack so I can know if there are any issues with the preflight process getting started.

**Comment by dustinryerson** [comment]
I've verified that this has been deployed to production. Please feel free to reopen if I've missed something.
