### ISSUE TITLE
builds page never finishes populating

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#267]
after force-reloading at `/#/builds`, spinners for all the builds appear and are never replaced with actual content. (This is the same for the list view.)

![Screen Shot 2020-10-08 at 10 15 35 AM](https://user-images.githubusercontent.com/303051/95492108-754d5200-094f-11eb-8086-7f952045010d.png)

**Comment by dustinryerson** [comment]
The spinners indicated that the build was in progress, however they've been replaced by different data, so this will no longer be an issue.
