### ISSUE TITLE
Filter by URL when clicking on on Health Status in a build

### ISSUE THREAD

**Issue by bdelano** [joyent/conch-ui#274]
Currently when you click on the health status it just brings you to the device page.  It would be nice if when you clickedon 'Fail' for example it brings you to the device page but automatically sets the filter for fail.... If we can represent this in a url it would be great, so could then someone a url with all the failed devices in a build....

e.g.
https://conch.joyent.us/#/builds/c19e26f8-04d7-4ebb-b29b-121fc6bc188a/devices?health=fail&phase=all&q=

**Comment by dustinryerson** [comment]
I've verified that this has been added to production. Please feel free to reopen if I've missed something.
