### ISSUE TITLE
Builds pane should show more information

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#286]
- started, completed timestamps are not viewable in the builds overview
- it is not possible to sort by name, nor timestamps
- "all" is the same thing as "created" - there is no such thing as a build that isn't created

Note you can make use of the query parameters in GET /build to constrain the search to just started or unstarted builds, or just completed or incomplete builds.

When completed_status is available in v3.0.6, that field should be viewable in the overview as well.

**Comment by dustinryerson** [comment]
The requested changes have been made and deployed to production.
