### ISSUE TITLE
Start making `/workspace/:wid/*` endpoints read only 

### ISSUE THREAD

**Issue by perigrin** [joyent/conch-ui#70]
This is a more general version of #58. Basically on the API side we have a bunch of duplicate logic for manipulating resources and that shouldn’t be, we should have one canonical way and the workspace specific resources should be read only.

We need to audit the UI code for where we POST to the API and make sure that’s happening on the more generic UIs.

**Comment by karenetheridge** [comment]
Let me know when I can remove these api endpoints:

```
POST    /workspace/:workspace_id_or_name/rack
DELETE  /workspace/:workspace_id_or_name/rack/:rack_id
POST    /workspace/:workspace_id_or_name/rack/:rack_id/layout
PUT     /workspace/:workspace_id_or_name/room
```

**Comment by sungo** [comment]
This will need shell work too. Is there a corresponding API ticket yet that I can reference?

**Comment by karenetheridge** [comment]
there is now.

**Comment by karenetheridge** [comment]
(copied from https://github.com/joyent/conch-shell/issues/200)

Note that the equivalent non-workspace command to `POST /workspace/:workspace_id_or_name/rack/:rack_id/layout` is `POST /device/:device_id/location`, but the latter requires the device to be already created, whereas the former will create the device for you as needed (using the hardware_product_id from the layout). Operators may depend on the device instantiation path (e.g. to create a device that we anticipate will start sending reports soon), so if so, we'll need to alter the functionality of `POST /device/:device_id/location` accordingly. Let me know!

**Comment by perigrin** [comment]
I think this is resolving itself by the removal of workspaces entirely. I'm gonna close, we can re-open if that's not true.
