### ISSUE TITLE
 handle changes to hardware_product_profile schema in 2.23

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#76]
https://github.com/joyent/conch/pull/626 changed the name of some existing fields in the `hardware_product_profile` table, and added a few more. Endpoints that deal with this table will need to have their expectations adjusted.

**Comment by dustinryerson** [comment]
@karenetheridge `conch-ui` only uses the hardware_product endpoint. Do the changes from https://github.com/joyent/conch/pull/626 affect hardware_product or just hardware_product_profile?

**Comment by karenetheridge** [comment]
`hardware_product_profile` data is contained in the hardware_product endpoints:  see
https://github.com/joyent/conch/blob/master/json-schema/response.yaml#L553
https://github.com/joyent/conch/blob/master/json-schema/input.yaml#L364
https://github.com/joyent/conch/blob/master/json-schema/input.yaml#L495

**Comment by dustinryerson** [comment]
Thanks for the info @karenetheridge. After looking through those references and the UI code, I don't believe any changes will need to be made to the UI for the v2.23 conch release. The UI only uses `hardware_product.id` and `hardware_product.name`.

**Comment by perigrin** [comment]
Unless there are other issues that are found in testing I don't think any work here is actually necessary for 2.23 support. Closing unless we find out otherwise.
