### ISSUE TITLE
Validations tab breaks when the device report contains validation results mapping to deactivated validations

### ISSUE THREAD

**Issue by dustinryerson** [joyent/conch-ui#80]
The Validations tab on the Device Inspector breaks (displays loading indicator infinitely). An error is displayed in the browser dev tools console.

The fix will be to grab deactivated validations using the `GET /validation/:id` endpoint if the validationId from the validation result does not match any of the active validations returned by the `GET /validations` endpoint.

**Comment by karenetheridge** [comment]
You shouldn't need to fall back to the single-validation endpoint - both `GET /validation` and `GET /validation/:id` now return information about deactivated validations as well. (Note the new column added to the response payload.)

See joyent/conch#674

**Comment by dustinryerson** [comment]
@karenetheridge thank you! Closing because joyent/conch#674 resolves this.
